### PR TITLE
Swap to GHA

### PR DESCRIPTION
**Pull request by adamgreig**
First go at GHA. I think the other books will be significantly harder due to more extensive CI, so this one first seems like a good starting point. :crossed_fingers:

### CODE REVIEW

**Comment by adamgreig** [comment]
Ok, the final step in testing is to merge this PR and see if it pushes a new build of the book. Ready to go as far as I can tell.

**Review by therealprof — APPROVED** [review]
LGTM, let's give it a spin.

bors r+

**Comment by adamgreig** [comment]
What's bors waiting for :thinking:

**Comment by therealprof** [comment]
Better times, aren't we all? 😅

**Comment by adamgreig** [comment]
bors retry

**Comment by adamgreig** [comment]
Oh, well, it wasn't bors' fault, I hadn't updated bors.toml to use GHA instead of Travis.

**Comment by therealprof** [comment]
Gosh, sorry for note noticing earlier.

**Comment by adamgreig** [comment]
Could you re-approve?

**Review by therealprof — APPROVED** [review]
bors r+

**Comment by adamgreig** [comment]
Seems to have worked and re-deployed!

**Comment by eldruin** [comment]
Great! thank you!

**Pull request merged**
