### PR TITLE
Make attributes visible in c-tips chapter

### LINKED ISSUE #211: Examples in intro for C developers lack attributes
It seems like the lines with attributes (i.e. `cfg` switches) are being dropped when rendered:

missing_attr

### PR DESCRIPTION
**Pull request by austinglaser**
Fixes #211

### CODE REVIEW

**Comment by andre-richter** [comment]
In my browser (Firefox) they are rendered:

image

**Comment by adamgreig** [comment]
I also see them render OK in Chrome; what browser are you using @austinglaser ?

**Comment by austinglaser** [comment]
Firefox 70.0.1, on ubuntu. I don't have any custom styles enabled.

If you build from my branch, does the chapter mis-render on your browsers?

**Comment by andre-richter** [comment]
> Firefox 70.0.1, on ubuntu. I don't have any custom styles enabled.
> 
> If you build from my branch, does the chapter mis-render on your browsers?

Same browser here, to the last digit. Ubuntu 64bit.

**Comment by austinglaser** [comment]
If I look at the page source for one of the offending examples, I see:

```html
<pre><pre class="playpen"><code class="language-rust">
<span class="boring">#![allow(unused_variables)]
fn main() {
</span>/// In your top-level lib.rs

<span class="boring">[cfg(feature=&quot;FIR&quot;)]
</span>pub mod fir;

<span class="boring">[cfg(feature=&quot;IIR&quot;)]
</span>pub mod iir;
<span class="boring">}
</code></pre></pre>
```

What do you see there on your system?

**Comment by austinglaser** [comment]
I see the same behavior (and the same static html, including `boring` spans) when building `master` locally with `mdbook` v0.3.4. Do I need to provide any additional arguments/configuration to `mdbook` other than `mdbook serve` in the root directory?

I've tried explicitly clearing my browser's cache, and I see the same page.

I'm looking at https://rust-embedded.github.io/book/c-tips/index.html. Is there another hosting location for the book that could cause this confusion?

Are there other things I could check? Does `mdbook` use `rustdoc` internally -- could that be a source of version mismatches? The rendering you're seeing seems like it's likely to come from a newer version of the tool which is smarter about attributes -- but the fact that I see this on the public site would seem to indicate that it's unlikely to be solely an issue with tooling versions on my system.

**Comment by adamgreig** [comment]
Ah, I'm looking at https://docs.rust-embedded.org/book/c-tips/index.html which renders OK, whereas your link to rust-embedded.github.io does not render correctly (with the attributes missing).

**Comment by austinglaser** [comment]
There it is! Your link renders fine for me as well.

That probably means we should hold off on merging this until verifying that the changes render correctly when they eventually get pushed to the rust-embedded.org site.

Also, I've found a couple other places in the book where attributes are mistakenly getting swallowed -- I'll add them to this PR as well.

**Comment by adamgreig** [comment]
This repository is configured to serve this repository's `gh-pages` branch at the rust-embedded.github.io link, and the gh-pages clearly has the `boring` spans: https://github.com/rust-embedded/book/blob/gh-pages/c-tips/index.html

Meanwhile the `docs` repository's `gh-pages` branch is hosted at docs.rust-embedded.org and also has CI build this repository, which does _not_ have the `boring` tags: https://github.com/rust-embedded/docs/blob/gh-pages/book/c-tips/index.html

I suspect the problem is that `docs` uses mkbook 0.2.1:

https://github.com/rust-embedded/docs/blob/master/ci/install.sh

while `book` uses latest:

https://github.com/rust-embedded/book/blob/master/ci/install.sh

**Comment by austinglaser** [comment]
I've opened a PR to make the `mdbook`  on `docs` the same as `book`. Additionally, I've fixed what I _think_ are all the occurrences of erroneously-swallowed code in examples (at least `rg boring book` after a build doesn't turn up any offenders

**Comment by austinglaser** [comment]
It looks like this is fixed in mdbook v0.3.5: https://github.com/rust-lang/mdBook/pull/1088

**Comment by adamgreig** [comment]
Thanks for chasing this down, @austinglaser!

**Pull request closed without merging**
