### PR TITLE
explain gdb again in "hardware"

### PR DESCRIPTION
**Pull request by utaal**
for folks who skipped / got distracted in the "QEMU" section

### CODE REVIEW

**Comment by utaal** [comment]
The note this is copied from, https://github.com/rust-embedded/book/blame/b370fa289a7f3a158266785cd8e7695412c25957/src/start/qemu.md#L479 in "QEMU", uses this format. Should I change that one as well to "> NOTE bla bla"?

**Comment by korken89** [comment]
Sorry for the late reply!
Yes, please do - better to be consistent :)

**Comment by jamesmunns** [comment]
Hey @utaal, are you interested in making the requested changes still?

**Comment by rubberduck203** [comment]
I was just about to submit this PR when I noticed this.
What changes were you looking for on this?

**Comment by utaal** [comment]
I... think I submitted this either with the web ui or from a clone I don't have anymore, and I don't know how (or, if I can) make changes to the PR at this stage: GitHub says "utaal wants to merge 1 commit  into rust-embedded:master from unknown repository", so I wouldn't know where to push additional changes. Shall we close this in favour of a new one?

**Pull request closed without merging**
