### PR TITLE
Update linux.md

### PR DESCRIPTION
**Pull request by flip111**
https://github.com/rust-embedded/book/issues/136

https://github.com/rust-embedded/book/issues/137

### CODE REVIEW

**Comment by Disasm** [comment]
Ping from triage: @thejpster, could you review this?

**Comment by DanHatesNumbers** [comment]
Just an FYI, OpenOCD is now available in the Community repo for Arch Linux and can't be installed from the AUR.

https://www.archlinux.org/packages/community/x86_64/openocd/

**Comment by korken89** [comment]
Ah, missed the issue with AUR @flip111 can you update?

**Comment by Disasm** [comment]
@korken89 it's already done in #179

**Comment by Disasm** [comment]
Resolved conflicts and updated

**Pull request merged**
