### PR TITLE
Add basic contributor's page based on git commit history

### PR DESCRIPTION
**Pull request by Nicoretti**
* Add inital contributor's page
* Add script to generate conributors page

Related Issues:
* https://github.com/rust-embedded/book/issues/123

### CODE REVIEW

**Comment by Nicoretti** [comment]
@jamesmunns I've seen the https://github.com/rust-embedded/book/issues/123 you created, this PR might be a first start to address this issue. The script `contributors.sh` could be extended and hooked up with the ci.

greez
Nico

**Comment by therealprof** [comment]
Hm, there're some duplicates in the contributors list. Also some people might prefer to be mentioned by their nick instead of their specified real name. We might have to do some postprocessing here, otherwise looks good to me.

**Comment by Nicoretti** [comment]
@therealprof sure, thing I was anyway meant a draft to discuss up on. I'm could think of adding mappings for e.g. the nicknames. However if it shall be more complex I would prefer to do it 
e.g. in python instead of using a shell script.

**Comment by therealprof** [comment]
Using Python should be fine.

**Comment by jamesmunns** [comment]
Hey @Nicoretti, thank you for the contribution! I'll do a quick vote of @rust-embedded/resources to see if we want to recognize people in this way.

If so, we can figure out some of the details around duplication, automation, etc.

- [ ] @adamgreig 
- [ ] @ryankurte 
- [ ] @korken89 
- [ ] @thejpster 
- [ ] @jamesmunns 
- [ ] @therealprof

**Comment by jamesmunns** [comment]
CC @japaric - this would be another place where "bors runs some kind of script on every merge to master" would be useful.

**Comment by adamgreig** [comment]
Given the issues around duplication, people potentially not wanting their email address linked to, and not being able to have bors run a script yet, I think my vote would be to not have the Python script in the repo, but to run it once to generate a list of names, and then manually maintain the list and suggest new contributors add themselves to it if they want to when they submit PRs.

I'd probably have either a list of names or names linked to GitHub profiles, rather than email addresses.

**Pull request closed without merging**
