### PR TITLE
Type-State Programming Chapter

### PR DESCRIPTION
**Pull request by jamesmunns**

### CODE REVIEW

**Comment by jamesmunns** [comment]
Reping @rust-embedded/resources - this chapter is now ready for review.

**Comment by jamesmunns** [comment]
Once #58 lands, I'll rebase my PR on that so CI will work

**Comment by jamesmunns** [comment]
Thanks!

**Comment by therealprof** [comment]
Was the rebase really necessary though? I thought bors try would automatically merge the master and the change into the try branch.

**Comment by jamesmunns** [comment]
hmm, you're probably right. I forgot bors does merge-then-test, not test-then-merge. Thanks anyway :)

**Pull request merged**
